### PR TITLE
Fix samples on OS X/iOS

### LINKED ISSUE #1: Problems building samples on OS X
I had some problems getting the following samples to compile on OS X 10.11.1 with Xcode 7.1.1:
- ocvColorQuantize
- ocvFaceDetect 
- ocvOpticalFlow
- ocvPerspective
- ocvWarp

They all had problems finding the boost libs:

```
../../../../../include/cinder/Filesystem.h:35:11: error: 'boost/filesystem.hpp' file not found with <angled> include; use "quotes" instead
        #include <boost/filesystem.hpp>
                 ^~~~~~~~~~~~~~~~~~~~~~
                 "boost/filesystem.hpp"
In file included from /Users/amorton/projects/Cinder/blocks
```

It seems like the fix for that is to change the "Header Search Path" to `"$(CINDER_PATH)/include"`. 

~~Changing that fixed all but the ocvFaceDetect sample which still had another error:~~

```
Undefined symbols for architecture x86_64:
  "cinder::app::Platform::getAssetPath(boost::filesystem::path const&) const", referenced from:
      cinder::app::AppBase::getAssetPath(boost::filesystem::path const&) const in ocvFaceDetectApp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

~~I'm not quite sure what to do about that.~~

### PR DESCRIPTION
**Pull request by drewish**
- Corrects the header search paths for boost

fixes #1

### CODE REVIEW

**Comment by andrewfb** [comment]
Thanks for these fixes...
