### ISSUE TITLE
Problems building samples on OS X

### ISSUE THREAD

**Issue by drewish** [cinder/Cinder-OpenCV3#1]
I had some problems getting the following samples to compile on OS X 10.11.1 with Xcode 7.1.1:
- ocvColorQuantize
- ocvFaceDetect 
- ocvOpticalFlow
- ocvPerspective
- ocvWarp

They all had problems finding the boost libs:

```
../../../../../include/cinder/Filesystem.h:35:11: error: 'boost/filesystem.hpp' file not found with <angled> include; use "quotes" instead
        #include <boost/filesystem.hpp>
                 ^~~~~~~~~~~~~~~~~~~~~~
                 "boost/filesystem.hpp"
In file included from /Users/amorton/projects/Cinder/blocks
```

It seems like the fix for that is to change the "Header Search Path" to `"$(CINDER_PATH)/include"`. 

~~Changing that fixed all but the ocvFaceDetect sample which still had another error:~~

```
Undefined symbols for architecture x86_64:
  "cinder::app::Platform::getAssetPath(boost::filesystem::path const&) const", referenced from:
      cinder::app::AppBase::getAssetPath(boost::filesystem::path const&) const in ocvFaceDetectApp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

~~I'm not quite sure what to do about that.~~

**Comment by drewish** [comment]
Fixed the undefined symbols error by rebuilding my copy of Cinder. It seems like I'd pulled in some changes to master since I'd last rebuilt. The changes in #2 get all the samples working for me.

**Comment by drewish** [comment]
Since I was in here I decided to try to run the iOS samples and found the same header search path issue affected them as well. I corrected that but noticed ocvBasic and ocvCapture seem to be trying to link against some missing files:

```
clang: error: no such file or directory: '../../../lib/ios/libopencv_calib3d.a'
clang: error: no such file or directory: '../../../lib/ios/libopencv_contrib.a'
clang: error: no such file or directory: '../../../lib/ios/libopencv_core.a'
clang: error: no such file or directory: '../../../lib/ios/libopencv_features2d.a'
clang: error: no such file or directory: '../../../lib/ios/libopencv_flann.a'
clang: error: no such file or directory: '../../../lib/ios/libopencv_imgproc.a'
clang: error: no such file or directory: '../../../lib/ios/libopencv_legacy.a'
clang: error: no such file or directory: '../../../lib/ios/libopencv_ml.a'
clang: error: no such file or directory: '../../../lib/ios/libopencv_nonfree.a'
clang: error: no such file or directory: '../../../lib/ios/libopencv_objdetect.a'
clang: error: no such file or directory: '../../../lib/ios/libopencv_photo.a'
clang: error: no such file or directory: '../../../lib/ios/libopencv_stitching.a'
clang: error: no such file or directory: '../../../lib/ios/libopencv_video.a'
clang: error: no such file or directory: '../../../lib/ios/libopencv_videostab.a'
```

**Comment by Tenkir** [comment]
I'm having a similar problem, but there's so little documentation for these libraries it's impossible to figure out what the issue is. Did you ever solve this @drewish ?
